### ISSUE TITLE
When calling `listenTo` helper two times stop listening firebase

### ISSUE THREAD

**Issue by saitodisse** [cerebral/cerebral-module-firebase#5]
**When calling `listenTo` helper two times the firebase stop to listening to changes**. I have debuged and the `off()` function is properly called when is already listening - https://github.com/cerebral/cerebral-module-firebase/blob/master/lib/helpers.js#L28

This problem happens when I click on cerebral debugger and the `componentDidMount()` activate the firebase listeners again. I change the code with a simple `if` and it works. _Do not listen again if already listening_: https://github.com/saitodisse/cerebral-module-firebase/blob/5872847983d3f3e49c2d40568ca07e4b2e522911/lib/helpers.js#L26-L27

I believe that is not the best approach. Maybe some way to check if the listener is active from this module can be a better solution or make `off` function to work like in the `stopListen` method.

**Comment by saitodisse** [comment]
> This problem happens when I click on cerebral debugger and the componentDidMount() activate the firebase listeners again.

This happens because the `componentDidMount()` is inside a route. I have moved the `onChildAdded, onChildRemoved and onChildChanged` to the module who controls the routing and is not called anymore. I believe it is not good to listening on childs routes.

**Comment by christianalfoni** [comment]
Hi @saitodisse and thanks for testing and reporting :)

So just so I understand. You have a signal that triggers in `componentDidMount` and some action starts listening to `onChildAdded` etc. But this happens twice because the component mounts twice?

**Comment by saitodisse** [comment]
Hi @christianalfoni, thanks for the response. They only are called again when I **click on signal on debugger** and the event is on a `componentDidMount()` inside a child route. But this is not a problem. The problem is that when it called again stops to listening.

**Comment by saitodisse** [comment]
New updates, It is working properly.
The problem exist if I try to unlisten before listen.
The code could check for that before try to unlisten.
I will close this for now.
